name: receipt_manager
description: Receipt Manager

version: 1.1.7+610

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  card_swiper: ^3.0.1
  flutter_clean_architecture: ^6.0.2
  injectable: ^2.3.0
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3

  equatable: ^2.0.5
  flutter_slidable: ^4.0.0
  cupertino_icons: ^1.0.6
  settings_ui: ^2.0.2
  permission_handler: ^12.0.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  currency_picker: ^2.0.20
  intl: ^0.20.2
  flutter_neumorphic_plus: ^3.2.0
  flutter_multi_formatter: ^2.12.0

  flutter_bloc: ^9.1.1
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  # Web support for drift
  sqlite3: ^2.9.0
  animated_stack: ^0.3.3
  syncfusion_flutter_charts: ^30.1.42

  image_picker: ^1.0.4
  flutter_typeahead: ^5.2.0
  file_picker: ^10.2.0

  flutter_uploader: ^3.0.0-beta.4
  flutter_local_notifications: ^19.4.0
  saver_gallery: ^4.0.0
  logger: ^2.3.0

  # Modern state management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  drift_dev: ^2.28.0

  # Code generation
  riverpod_generator: ^2.4.0
  freezed: ^2.5.4
  json_serializable: ^6.8.0

  # Testing framework
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0

  flutter_native_splash: ^2.3.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  color_dark: "#ffffff"
  fullscreen: true

flutter_intl:
  enabled: true